[env]
TERM = "xterm-256color"

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
size = 14

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "N"
mods = "Control|Alt"

[keyboard.bindings.command]
args = ["msg", "config", "window.opacity=1.0"]
program = "alacritty"

[[keyboard.bindings]]
key = "T"
mods = "Control|Alt"

[keyboard.bindings.command]
args = ["msg", "config", "window.opacity=0.8"]
program = "alacritty"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"
mods = "Alt"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.footer_bar]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[shell]
program = "fish"

[window]
decorations = "full"
