#!/usr/bin/env bash


git clone https://github.com/vinceliuice/grub2-themes/ /tmp/grub2-themes
cd /tmp/grub2-themes

# Don't preserve ownership because the owner will be root, and that causes the script to crash if it is ran from terminal by sudo
cp -a --no-preserve=ownership ./common/{*.png,*.pf2} /boot/grub/themes/vimix/
cp -a --no-preserve=ownership ./config/theme-vimix.txt /booot/grub/themes/vimix/theme.txt
cp -a --no-preserve=ownership ./backgrounds/1080p/background-vimix.jpg /boot/grub/themes/vimix/background.jpg"

