#!/usr/bin/env bash

# starship
sh -c "$(curl -fsSL https://starship.rs/install.sh)"

# download oh-my-zsh and plugins

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting -q
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions -q
git clone https://github.com/hlissner/zsh-autopair $HOME/.zsh-autopair -q
rm -rf $HOME/.zshrc

# set dotfiles
cd $HOME/.dotfiles
STOW_FOLDERS="git,scripts,kitty,i3,zsh,tmux,wallpapers"

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

ln -s $HOME/.config/nvim $HOME/.vim
ln -s $HOME/.config/nvim/init.vim $HOME/.vimrc

echo "Install Sucefull"
