#!/usr/bin/env bash

# set dotfiles
cd $HOME/.dotfiles

mkdir $HOME/.local/bin

STOW_FOLDERS="nvim,scripts,zsh"

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

ln -s $HOME/.config/nvim $HOME/.vim
ln -s $HOME/.config/nvim/init.vim $HOME/.vimrc
