#!/usr/bin/env bash

# install home-manager
nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz home-manager 
nix-channel --update

# set dotfiles
cd $HOME/.dotfiles

mkdir $HOME/.local/bin

STOW_FOLDERS="nvim,scripts,nixos,zsh"

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

ln -s $HOME/.config/nvim $HOME/.vim
ln -s $HOME/.config/nvim/init.vim $HOME/.vimrc

echo "Run home-manager switch to Finish Instalation"
