abbr --add dc 'docker-compose'
abbr --add d 'docker'
abbr --add dev 'cd $HOME/Projects'
abbr --add clip 'xclip -selection clipboard'
abbr --add vim 'nvim'
abbr --add vi 'nvim -u $HOME/.dotfiles/nvim/ftplugin/cpp.lua'
