abbr --add dc 'docker-compose'
abbr --add d 'docker'
abbr --add vim 'nvim'
abbr --add db 'distrobox'

alias zz='cd $(find . -type d -print | fzf)'
alias vi='nvim -u $HOME/.dotfiles/nvim/cpp.lua '
alias cat='bat '
alias ls='eza --icons=always '
alias find='fd '
alias cd='z '
alias diff='difft '
